# Generated by Django 5.1.4 on 2025-02-12 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0002_substitute'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Substitute',
        ),
    ]
