# Generated by Django 5.1.4 on 2025-02-13 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='activity',
            field=models.CharField(choices=[('sedentary', 'sedentary'), ('light', 'light active'), ('moderate', 'moderate active'), ('very', 'very active')], max_length=20),
        ),
    ]
