# Generated by Django 5.1.4 on 2025-02-11 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodPreference', '0001_initial'),
        ('recipe', '0002_remove_recipe_ingredients_ingredientsdetails_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='allergies',
            field=models.ManyToManyField(blank=True, related_name='recipe_allergies', to='foodPreference.allergy'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='diet',
            field=models.ManyToManyField(blank=True, related_name='recipe_diet', to='foodPreference.diet'),
        ),
    ]
