# Generated by Django 5.1.4 on 2025-02-12 15:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0003_recipe_allergies_recipe_diet'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='favourite',
            field=models.ManyToManyField(blank=True, related_name='favourite_recipe', to=settings.AUTH_USER_MODEL),
        ),
    ]
