# Generated by Django 5.1.4 on 2025-02-13 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0004_recipe_favourite'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='dish_type',
            field=models.CharField(choices=[('breakfast', 'breakfast'), ('starter', 'starter'), ('main', 'main'), ('dessert', 'dessert')], default='main', max_length=10),
        ),
    ]
