# Generated by Django 5.1.4 on 2025-02-13 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0005_recipe_dish_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='dish_type',
        ),
    ]
